version: 2.1
executors:
  python:
    docker:
      - image: cfmanteiga/alpine-bash-curl-jq

jobs:
  deploy:
    executor: python
    steps:
      - checkout
      - run: ln -s /bin/bash /bin/sh -f
      - run: sh deploy.sh
workflows:
  approved_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
