version: 2.1
executors:
  python:
    docker:
      - image: bashell/alpine-bash
jobs:
  deploy:
    executor: python
    steps:
      - checkout
      - run: sh deploy.sh
      - run: sleep 3
      - run: sh deploy_success.sh
workflows:
  approved_deploy:
    jobs:
      - deploy
