version: 2.1
executors:
  python:
    docker:
      - image: cfmanteiga/alpine-bash-curl-jq

commands:
  test:
    parameters:
      value:
        type: string
    steps:
      - run:
          name: echo
          command: echo "<< parameters.value >>"

jobs:
  deploy:
    executor: python
    steps:
      - checkout
      # - run: ln -s /bin/bash /bin/sh -f
      # - run: sh deploy.sh
      - test:
          value: foo=${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/foo:${CIRCLE_WORKFLOW_ID} bar=${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/bar:${CIRCLE_WORKFLOW_ID}

workflows:
  approved_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
