version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6
jobs:
  deploy:
    executor: python
    steps:
      - checkout
      - run: sh deploy.sh
workflows:
  approved_deploy:
    jobs:
      - deploy
